name: Create Release When Changelog Changes
on:
  push:
    branches: [ master ]
    paths:
      - 'CHANGELOG.md'
  workflow_dispatch:
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get last version from tag
        id: lasttag
        shell: bash
        run: echo ::set-output name=version::$(git describe --abbrev=0 --tags --match '[0-9]*\.[0-9]*\.[0-9]*')
      - uses: coditory/changelog-parser@v1
        id: changelog
      - if: ${{ steps.changelog.outputs.version != steps.lasttag.outputs.version }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{ steps.changelog.outputs.description }}
          tag_name: ${{ steps.changelog.outputs.version }}
          release-name: ${{ steps.changelog.outputs.version }}
