name: Create Release When Changelog Changes
on:
  push:
    branches: [ master ]
    paths:
      - 'CHANGELOG.md'
  workflow_dispatch:
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get last version from tag
        id: lasttag
        shell: bash
        run: echo ::set-output name=version::$(git describe --abbrev=0 --tags --match '[0-9]*\.[0-9]*\.[0-9]*')
      - uses: coditory/changelog-parser@v1
        id: changelog
      - if: ${{ steps.changelog.outputs.version != steps.lasttag.outputs.version }}
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.changelog.outputs.description }}
          prerelease: true
          tag: ${{ steps.changelog.outputs.version }}
          token: ${{ secrets.CREATE_RELEASE }}
      - uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "https://github.com/skynet-gh/skylobby/releases/tag/${{ steps.changelog.outputs.version }}\n\n${{ steps.changelog.outputs.description }}"
