name: Build GitHub Pages Cryogen
on:
  push:
    branches: [ master ]

  workflow_dispatch:
jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm-version: 'vm-21.3.0'
          java: 'java11'
      - uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: '1.10.3.998'
      - run: clojure -M:build
        working-directory: ./cryogen
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cryogen/public/skylobby
