name: Build GitHub Pages Cryogen
on:
  push:
    branches: [ master ]

  workflow_dispatch:
jobs:
  pages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'zulu'
      - uses: DeLaGuardo/setup-clojure@3.7
        with:
          cli: latest
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('cryogen/project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: clojure -M:build
        working-directory: ./cryogen
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cryogen/public/skylobby
