name: Build Release Artifacts

on:
  release:
    types: [created]

jobs:
  build-deb:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v2.3.0
      - uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'zulu'
      - uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: '1.10.3.998'
      - run: clojure -M:uberjar:headless
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/${{ env.CI_REPOSITORY_NAME }}.jar
          asset_name: ${{ env.CI_REPOSITORY_NAME }}-${{ env.CI_REF_NAME }}-linux.jar
          asset_content_type: application/java-archive
      - run: jpackage --app-version ${{ env.CI_REF_NAME }} @jpackage/lobby @jpackage/linux
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.CI_REPOSITORY_NAME }}_${{ env.CI_REF_NAME }}-1_amd64.deb
          asset_name: ${{ env.CI_REPOSITORY_NAME }}-${{ env.CI_REF_NAME }}_linux-amd64.deb
          asset_content_type: application/vnd.debian.binary-package
        #      - run: rm dist/*
        #      - run: clojure -M:uberjar:headless --main-class 'spring-lobby.replays' --jar 'dist/skyreplays.jar'
        #      - uses: actions/upload-release-asset@v1.0.2
        #        env:
        #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #        with:
        #          upload_url: ${{ github.event.release.upload_url }}
        #          asset_path: ./dist/skyreplays.jar
        #          asset_name: skyreplays-${{ env.CI_REF_NAME }}-linux.jar
        #          asset_content_type: application/java-archive
        #      - run: jpackage --app-version ${{ env.CI_REF_NAME }} @jpackage/replays @jpackage/linux
        #      - uses: actions/upload-release-asset@v1.0.2
        #        env:
        #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #        with:
        #          upload_url: ${{ github.event.release.upload_url }}
        #          asset_path: ./skyreplays_${{ env.CI_REF_NAME }}-1_amd64.deb
        #          asset_name: skyreplays-${{ env.CI_REF_NAME }}_linux-amd64.deb
        #          asset_content_type: application/vnd.debian.binary-package
  build-dmg:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v2.3.0
      - uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'zulu'
      - uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: '1.10.3.998'
      - run: clojure -M:uberjar:headless
        #      - uses: actions/upload-release-asset@v1.0.2
        #        env:
        #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #        with:
        #          upload_url: ${{ github.event.release.upload_url }}
        #          asset_path: ./dist/${{ env.CI_REPOSITORY_NAME }}.jar
        #          asset_name: ${{ env.CI_REPOSITORY_NAME }}-${{ env.CI_REF_NAME }}-mac.jar
        #          asset_content_type: application/java-archive
      - run: jpackage --app-version ${{ env.CI_REF_NAME }} @jpackage/lobby @jpackage/mac
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.CI_REPOSITORY_NAME }}-${{ env.CI_REF_NAME }}.dmg
          asset_name: ${{ env.CI_REPOSITORY_NAME }}-${{ env.CI_REF_NAME }}_mac.dmg
          asset_content_type: application/x-apple-diskimage
          #      - run: rm dist/*
        #      - run: clojure -M:uberjar:headless --main-class 'spring-lobby.replays' --jar 'dist/skyreplays.jar'
        #      - uses: actions/upload-release-asset@v1.0.2
        #        env:
        #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #        with:
        #          upload_url: ${{ github.event.release.upload_url }}
        #          asset_path: ./dist/skyreplays.jar
        #          asset_name: skyreplays-${{ env.CI_REF_NAME }}-mac.jar
        #          asset_content_type: application/java-archive
        #      - run: jpackage --app-version ${{ env.CI_REF_NAME }} @jpackage/replays @jpackage/mac
        #      - uses: actions/upload-release-asset@v1.0.2
        #        env:
        #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #        with:
        #          upload_url: ${{ github.event.release.upload_url }}
        #          asset_path: ./skyreplays-${{ env.CI_REF_NAME }}.dmg
        #          asset_name: skyreplays-${{ env.CI_REF_NAME }}_mac.dmg
        #          asset_content_type: application/x-apple-diskimage
  build-exe:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v2.3.0
      - uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'zulu'
      - run: iwr -useb download.clojure.org/install/win-install-1.10.3.998.ps1 | iex
      - run: clojure -M:uberjar:headless
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/${{ env.CI_REPOSITORY_NAME }}.jar
          asset_name: ${{ env.CI_REPOSITORY_NAME }}-${{ env.CI_REF_NAME }}-windows.jar
          asset_content_type: application/java-archive
      - run: cp package/win/* dist
      - run: jpackage --app-version ${{ env.CI_REF_NAME }} @jpackage/lobby @jpackage/windows
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.CI_REPOSITORY_NAME }}-${{ env.CI_REF_NAME }}.msi
          asset_name: ${{ env.CI_REPOSITORY_NAME }}-${{ env.CI_REF_NAME }}_windows.msi
          asset_content_type: application/x-msi
        #      - run: rm dist/*
        #      - run: clojure -M:uberjar:headless --main-class 'spring-lobby.replays' --jar 'dist/skyreplays.jar'
        #      - uses: actions/upload-release-asset@v1.0.2
        #        env:
        #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #        with:
        #          upload_url: ${{ github.event.release.upload_url }}
        #          asset_path: ./dist/skyreplays.jar
        #          asset_name: skyreplays-${{ env.CI_REF_NAME }}-windows.jar
        #          asset_content_type: application/java-archive
        #      - run: jpackage --app-version ${{ env.CI_REF_NAME }} @jpackage/replays @jpackage/windows
        #      - uses: actions/upload-release-asset@v1.0.2
        #        env:
        #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #        with:
        #          upload_url: ${{ github.event.release.upload_url }}
        #          asset_path: ./skyreplays-${{ env.CI_REF_NAME }}.msi
        #          asset_name: skyreplays-${{ env.CI_REF_NAME }}_windows.msi
        #          asset_content_type: application/x-msi
